
var keysTranslation:[String:String] = [
    "email_or_mobile":"رقم الهاتف او البريد الالكتروني",
    "password":"كلمة المرور",
    "forget_password":"نسيت كلمة المرور",
    "login":"تسجيل دخول",
    "register":"تسجيل جديد",
    "sign":"تسجيل",
    "login_with_facebook":"التسجيل بواسطة الفيسبوك",
    "icPersonAdd":"icPersonAdd",
    "icFacebook":"icFacebook",
    "backEn":"back",
    "menuEn":"menu",
    "name":"الاسم",
    "email":"البريد الإلكتروني",
    "mobile":"رقم الهاتف",
    "confirmation_password":"إعادة كلمة المرور",
    "confirm_password":"إعادة كلمة المرور",
    "set_your_location":"قم بتحديد الموقع",
    "city":"المدينة",
    "district":"المنطقة",
    "show_restaurant":"عرض المطاعم",
    "your_registration_request_has_been_sent":"تم إرسال طلب التسجيل",
    "Your account will be activated from the administration after which you will be received Activation email You registered it":"سيتم تفعيل حسابك من الادارة بعدها سيصلك رسالة بالتفعيل على بريدك الإلكتروني الذي قمت بالتسجيل به",
    "ok":"حسنأ",
    "search_in_city":"ابحث عن المدينة",
    "search_in_district":"ابحث عن منطقة",
    "location":"موقعك",
    "search_in_chiefs":"ابحث عن أحد المطابخ أو الأطباق",
    "best_chiefs":"المطابخ المميزة",
    "show_all":"عرض الكل",
    "nearest_chiefs":"المطابخ القريبة منك",
    "categories":"الفئات",
    "adEn":"adAr",
    "minute":"دقيقة",
    "show_result":"عرض النتائج",
    "chief_type":"نوع المطبخ",
    "sort_by":"ترتيب حسب",
    "chiefs_filters":"فرز المطابخ",
    "cancel":"الغاء",
    "agree":"موافق",
    "accept":"قبول",
    "address":"العنوان",
    "total_price:_":"إجمالي الطلب :",
    "delivery_cost:_":"سعر خدمة التوصيل :",
    "follow_the_order":"متابعة الطلب",
    "order_now":"أطلب الآن",
    "offers":"العروض",
    "cart":"السلة",
    "SR":"ريال",
    "add_to_cart":"أضف الى السلة",
    "search":"بحث",
    "about":"حول",
    "menu":"قائمة الطعام",
    "rate":"التقييم",
    "description":"وصف",
    "minimum_order":"الحد الادنى للطلب",
    "delivery_cost":"سعر خدمة التوصيل",
    "total_price":"اجمالي الطلب",
    "all":"الكل",
    "default":"افتراضي",
    "maximum_price_in_minimum_order":"الأكثر سعراً فى الحد الأدنى للطلب",
    "loawest_price_in_minimum_order":"الأقل سعراً فى الحد الأدنى للطلب",
    "fast_delivery":"الأسرع فى توصيل الطلب",
    "top_rate":"الأعلى تقييماً",
    "icArrowBlackAr":"icArrow",
    "arrowEn":"arrow",
    
    "street":"الشارع",
    "continue_shopping":"مواصلة التسوق",
    "follow_your_request_here":"تابع طلبك هنا",
    "order_number:_":"رقم الطلب : ",
    "order_number":"رقم الطلب",
    "order_send_successfully":"تم إرسال طلب بنجاح",
    "send_order":"إرسال الطلب",
    "flat_number_(_optinal_)":"رقم الشقة (إختياري)",
    "number_of_building":"رقم أو اسم العمارة",
    
    "Note The delivery rate will change if you change the city and region":"ملحوظة سيتم تغير سعر التوصيل في حالة التعديل علي المدينة والمنطقة",
    "region_displaing_here":"المنطقة تعرض وتكتب هنا",
    "city_displaing_here":"المدينة تعرض وتكتب هنا",
    "chief_is:_":"يقدمها لك مطبخ :",
    
    
    "orders":"الطلبات",
    "upcoming":"الحالية",
    "previous":"السابقة",
    "there_are_no_current_orders":"لا توجد طلبات حالية",
    "ask_for_your_favorite_food_now":"اطلب طعامك المفضل الان",
    "show_order_details":"عرض تفاصيل الطلب",
    "give_us_your_opinion":"اعطنا رأيك",
    "later":"لاحقاً",
    "order_date":"تاريخ الطلب",
    "order_detail":"تفاصيل الطلب",
    "follow_the_status_of_your_order":"تابع حالة طلبك",
    "price":"السعر",
    "order_status":"حالة الطلب",
    "send":"إرسال",
    "favorites":"المفضلة",
    "app_language":"لغة التطبيق",
    "contact_us":"اتصل بنا",
    "about_app":"عن التطبيق",
    "usage_policy":"سياسة الاستخدام",
    "share_app":"مشاركة التطبيق",
    "profile":"الملف الشخصي",
    "my_profile":"بيانات حسابي",
    "edit_password":"تعديل كلمة المرور",
    "logout":"تسجيل خروج",
    "save":"حفظ",
    "old_password":"كلمة المرور القديمة",
    "new_password":"كلمة المرور الجديدة",
    "confirmation_new_password":"إعادة كلمة المرور الجديدة",
    "email_us":"راسلنا عبر البريد الإلكتروني",
    "submit_a_suggestion":"إرسال مقترح",
    "submit_a_complain":"إرسال شكوى",
    "what_is_your_suggestion":"ما هو اقتراحك",
    "the_text_of_the_complaint":"نص الشكوى",
    "camera":"الكاميرا",
    "gallery":"المعرض",
    "choose_image":"اختر صورة",
    "you_don't_have_camera":"عفوا ليس لديك كاميرا",
    "warning":"انذار",
    "update":"تعديل",
    "delete":"حذف",
    "update_profile":"تعديل بياناتي",
    "waiting_to_accept":"في انتظار الموافقة",
    "processing_your_order":"جاري تجهيز طلبك",
    "delivering_your_order":"جاري توصيل طلبك",
    "your_order_is_deliveried":"تم توصيل طلبك",
    "you_order_is_received":"تم استلامها",
    "Designed and Developed by ATIAF Integrated Solutions":"تصميم وتطوير شركة أطياف للحلول المتكاملة",
    "عربي":"english",
    "english":"عربي",
    "does_not_match":"غير متطابق",
    "this_field_is_required":"هذا الحقل مطلوب",
    "must_be_a_valid_email_address":"يجب ان يحتوي علي بريد الكتروني صحيح",
    "login_success":"تم تسجيل الدخول بنجاح",
    "logout_success":"تم تسجيل الخروج بنجاح",
    "code":"رمز التفعيل",
    "updated_successfully":"تم التعديل بنجاح",
    "reset_successfully":"تم استعادة كلمة السر",
    "Dear Customer Design has been sent to you to pay the agreed price to download the design":"عزيزي العميل تم إرسال التصميم عليك بدفع السعر المتفق عليه  لتحميل التصميم",
    
    "select_the_price_setting_by_the_designer":"سيتم تحديد السعر من قبل المصمم",
    "your_rate":"تقييمك",
    "no_rate":"لم يتم التقييم",
    "first_name":"الاسم الأول",
    "last_name":"الاسم الأخير",
    "phone":"رقم الهاتف",
    "enter_password":"أدخل كلمة المرور",
    "do_you_have_a_question_?":"هل لديك سؤال ؟",
    "send_message":"إرسال رسالة",
    "your_name":"أسمك",
    "your_email":"بريدك الإلكتروني",
    "subject":"الموضوع",
    "your_message":"رسالتك",
    "password_incorrect":"خطأ في كلمة السر",
    "confirmation_password_must_equal_password":"تاكيد كلمة السر يجب ان تطابق كلمة السر",
    "invalid_email":"البريد الألكتروني",
    "invalid_code":"رمز التفعيل خاطيء",
    "messages":"الرسائل",
    "message_detail":"محتوي الرسالة",
    "welcome_in":"مرحباً بك في",
    "login_for_continue":"سجل الدخول للمتابعة",
    "you_dont_have_an_account_?":"ليس لديك حساب سابقاً؟",
    "email_or_phone":"البريد الإلكتروني أو رقم الهاتف",
    "top_desingers_rate":"المصممين الأعلى تقييما",
    "last_added_desinges":"تصاميم تم اضافتهم حديثاً",
    "all_categories":"كل الفئات",
   
    
    "size":"المقاس",
    "color":"اللون",
    "quantity":"العدد",
    "near_me":"بالقرب مني",
    "welcome":"مرحباً بك",
    "choose_size":"اختر المقاس",
    "set_custom_size":"تحديد مقاس خاص",
    "choose_color":"اختر اللون",
    "choose_quantity":"حدد الكمية",
    "saved_addresses":"العناوين المحفوظة",
    "new_address":"عنوان جديد",
    "building_name":"اسم العمارة / المنزل ",
    "floor":"الطابق / الدور",
    "continue":"متابعة",
    "delivery_to":"يشحن إلى",
    "your_order":"طلبك",
    "note":"ملاحظة",
    "payment_summary":"ملخص الدفع",
    "total_order_:":"الطلب الكلي :",
    "delivery_cost_:":"رسوم التوصيل :",
    "total_price_:":"المبلغ الإجمالي :",
    "select_payment_method":"إختر طريقة الدفع",
    "cash_on_delivery":"الدفع عند الاستلام",
    "visa":"فيزا",
    
    "confirm_order":"تأكيد الطلب",
    "thank_you":"شكراً لك",
    "your_order_send_successfully":"تم ارسال طلبك بنجاح",
    "follow_your_order":"تتبع طلبك هنا",
    "request_custom_design":"طلب رسم تصميم",
    "model_type":"نوع الموديل",
    "model_tall":"طول الموديل",
    "shape":"الشكل",
    "sleeve_type":"نوع الأكمام",
    "Please specify the type of fabric and model details to be designed":"نرجوا ذكر نوع القماش وتفاصيل الموديل المراد تصميمه",
    "settings":"الإعدادات",
    "my_addresses":"قائمة العناوين",
    "notifications":"الإشعارات",
    "add_new_address":"اضافة عنوان جديد",
    "add":"اضافة",
    "done":"تم",
    "add_your_comment":"أضف تعليقك أو رأيك",
    "my_orders":"طلباتي",
    "order_number_:":"رقم الطلب :",
    "payment_method_:":"طريقة الدفع :",
    "order_status_:":"حالة الطلب :",
    "call":"اتصال",
    "cancel_order":"إلغاء الطلب",
    "request_design_fee":"طلب رسم تصميم",
    "model_type_:":"نوع الموديل :",
    "model_tall_:":"طول الموديل :",
    "shape_:":"الشكل :",
    "sleeve_:":"الأكمام :",
    "email_:":"بريد إلكتروني :",
    "download_design":"تحميل التصميم",
    "price_:":"السعر :",
    "about_us":"عن التطبيق",
    "paid":"دفع",
    "home":"الرئيسية",
    "info":"حول",
    "designes":"التصاميم",
    "comments":"التقييمات",
    "CM":"سم",
    "write_note_here":"اكتب ملاحظاتك هنا",
    "order_summary":"ملخص الطلب",
    "size_:":"المقاس :",
    "color_:":"اللون:",
    "quantity_:":"الكمية :",
    "payment":"الدفع",
    "there_are_currently_no_requests":"لا يوجد اي طلبات حالية الان",
    "my_location":"موقعي علي الخريطة",
    "arrowLeft":"arrowRight",
    "arrowRight":"arrowLeft",
    "register_done":"تم التسجيل بنجاح",
    "designers_login":"تسجيل دخول المصممين",
    "Terms and conditions of use":"شروط وأحكام الاستخدام",
    "I agree to the terms and conditions of use":"أنا أوافق على شروط وأحكام الاستخدام",
    "Important Alert":"تنبيه هام",
    "These terms and conditions are legally registered and when approved, you will have to comply with them and any complaint thereof will expose you to legal liability and thank you":"هذه الشروط والاحكام مسجله قانونياً وعند موافقة عليها يكون عليك الالتزام بها  واي مخالفه فيها ستعرضك للمسائلة القانونية وشكراً",
    "refuse":"رفض",
    "Name of designer or shop":"اسم المصمم او المحل",
    "Name of the responsible person":"اسم الشخص المسؤول",
    "Brief":"نبذة",
    "Add brief":"اضف نبذة",
    "services":"الخدمات",
    "select_your_service":"اختر الخدمة التي تقدمها",
    "set_location":"تحديد الموقع",
    "Your account will be activated from the administration. The activation message will then be sent to your e-mail address":"سيتم تفعيل حسابك من الادارة بعدها سيصلك رسالة بالتفعيل على بريدك الإلكتروني الذي  قمت بالتسجيل به",
    "Pending orders":"الطلبات المنتظرة",
    "Current orders":"الطلبات الحالية",
    "Previous orders":"الطلبات السابقة",
    "Evaluations and opinions":"التقييمات والآراء",
    "confirm":"تأكيد",
    "details":"تفاصيل",
    "shipping_details":"تفاصيل الشحن",
    "price_sent_:":"تم إرسال السعر :",
    "price_confirmed_:":"تم تأكيد السعر :",
    "start_work":"بدء العمل",
    "set_price":"حدد السعر",
    "charging":"جاري الشحن",
    "After processing the order, follow the following case":"بعد تجهيز الطلب قم بمتابعة الحالة التالية",
    "After charging the order, follow the following case":"بعد شحن الطلب قم بمتابعة الحالة التالية",
    "order shipped":"تم شحن الطلب",
    "order is processed":"تم تجهيز الطلب",
    "order sent":"تم ارسال الطلب",
    "design sent":"تم ارسال التصميم",
    "Send the design":"قم بارسال التصميم",
    "send_design":"إرسال التصميم",
    "design_link":"رابط التصميم",
    "finish":"انهاء",
    "rate_from":"تقييمك من",
    "add_new_design":"اضافة تصميم جديد",
    "service_type":"نوع الخدمة",
    "design_name":"اسم التصميم",
    "design_description":"وصف للتصميم",
    "edit_profile":"تعديل الحساب",
    "password_reset":"إعادة تعيين كلمة المرور",
    "edit_brief":"تعديل نبذة",
    "edit_location":"تعديل الموقع",
    "":"",
]



public func translate(_ key:String)->String{
    var newKey = key
    if newKey == "SR"{
        newKey = "SAR"
    }
    return LocalizationHelper.key(key)
}
public func translate(_ item:String?,_ key:String)->String{
    var itemNew = ""
    if(item != nil){
        itemNew = item!
    }
    var newKey = key
    if newKey == "SR"{
        newKey = "SAR"
    }
    return LocalizationHelper.key(item: itemNew, key)
}
public func translate(_ item:String?,_ key:String,_ orderable:Bool)->String{
    var itemNew = ""
    if(item != nil){
        itemNew = item!
    }
    var newKey = key
    if newKey == "SR"{
        newKey = "SAR"
    }
    return LocalizationHelper.key(item: itemNew, key, orderable: orderable)
}
public func initLang(){
    LocalizationHelper.initLang()
}
public func getAppLang()->String{
    return LocalizationHelper.getAppLang()
}
public func setAppLang(_ lang:String)->String{
    return LocalizationHelper.setAppLang(lang)
}
